version: "3.7"

services:
    velflix-fpm-service:
        build:
            context: ..
            dockerfile: devops/Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ../:/var/www
        networks:
            - laravel


    velflix-nginx-service:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ../:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    velflix-mysql-service:
        image: mysql:8
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_ROOT_HOST: "%"
        volumes:
            - mysql-data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - laravel
        ports:
            - "3306:3306"

networks:
    laravel:
        driver: bridge

volumes:
    mysql-data:
