pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'mahdi0188/velflix-fpm'  // Set your Docker Hub username/repository
        DOCKER_TAG = 'latest'                  // Set your tag (e.g., latest or commit SHA)
        DOCKER_CREDENTIALS_ID = 'mahdi0188-dockerhub' // Jenkins credentials ID for Docker Hub login
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from your repository
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                // Build the Docker image using a custom Dockerfile
                sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} -f devops/docker/prod-docker/Dockerfile.fpm ."
            }
        }


        stage('Push Docker Image') {
            steps {
                script {
                    // Push the Docker image to Docker Hub
                    sh "docker push ${DOCKER_IMAGE}:${DOCKER_TAG}"
                }
            }
        }
    }
}
