apiVersion: apps/v1
kind: Deployment

metadata:
  creationTimestamp: null
  labels:
    app: velflix-fpm
  name: velflix-fpm
  namespace: velflix-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velflix-fpm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: velflix-fpm
    spec:
      containers:
      - image: mahdi0188/velflix-fpm:dev-61-b8b8adc
        name: velflix-fpm
        resources: {}
status: {}
