apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: velflix-fpm
  name: velflix-fpm-service
  namespace: velflix-dev
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: velflix-fpm
status:
  loadBalancer: {}
